force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Max_Pay__c.field-meta.xml
<CustomField>
    <fullName>Max_Pay__c</fullName>
    <label>Max Pay</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Date__c</fullName>
    <label>Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Position</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Open - Approved</fullName>
            </value>
            <value>
                <fullName>Closed - Filled</fullName>
            </value>
            <value>
                <fullName>Closed - Not Approved</fullName>
            </value>
            <value>
                <fullName>Closed - Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PositionTriggerHandler.cls
public class PositionTriggerHandler {
    public static void populateData(List<Position__c> posList){
        for(Position__c pos: posList){
            if(pos.status__c == 'New Position'){
                if(pos.Open_Date__c == null){
                    pos.Open_Date__c = System.Today();
                }
                if(pos.Min_Pay__c == null){
                    pos.Min_Pay__c = 10000;
                }
                if(pos.Max_Pay__c == null){
                    pos.Max_Pay__c = 15000;
                }
            }
        }
    }
    
    public static void createTask(List<Position__c> posList){
        List<Task> taskList = new List<Task>();
        
        for (Position__c pos : posList){
            
            Task t = new Task();
            t.Subject= 'Follow up';
            t.ActivityDate = System.Today() + 7;
            t.WhatId = pos.Id;
            t.OwnerId = UserInfo.getUserId();
            t.Status = 'Not Started';
        }
    }
}